name: macOS + Nix

on: [push]

permissions:
  contents: read

jobs:
  test:
    name: Install on ${{ matrix.runs_on }} with Determinate Nix
    strategy:
      fail-fast: false
      matrix:
        runs_on: [macos-26, macos-15, macos-14]
    runs-on: ${{ matrix.runs_on }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install Determinate Nix
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Run install.sh
        run: |
          curl -sSf https://raw.githubusercontent.com/noor-latif/get-flox/${{ github.sha }}/install.sh | bash

      - name: Verify flox
        run: |
          flox --version
